(tool-bar-mode -1)
(menu-bar-mode -1)
(scroll-bar-mode -1)
(global-linum-mode 1)
(set-face-attribute 'default nil :height 110)
(global-hl-line-mode 1)
(setq-default cursor-type 'box)
(setq initial-frame-alist (quote ((fullscreen . maximized))))
