;;; project find file
(defun find-file-with-projectile-or-counsel-git ()
  (interactive)
  (if (git-project-root)
      (counsel-git)
    (if (projectile-project-p)
        (counsel-projectile-find-file)
      (counsel-file-jump))))

(defun git-project-root ()
  "Return the project root for current buffer."
  (let ((directory default-directory))
    (locate-dominating-file directory ".git")))

;; project find file ends here

(defun occur-dwim ()
  "Call `occur' with a sane default."
  (interactive)
  (push (if (region-active-p)
            (buffer-substring-no-properties
             (region-beginning)
             (region-end))
          (let ((sym (thing-at-point 'symbol)))
            (when (stringp sym)
              (regexp-quote sym))))
        regexp-history)
  (call-interactively 'occur))

(defun nicolas4d-base/user-config ()
  "for excute in dotspacemacs/user-config"
  ;;; customize key binding prefixes.
  (setq spacemacs/key-binding-prefixes '(("a"   "applications")
                                         ("ai"  "irc")
                                         ("as"  "shells")
                                         ("b"   "buffers")
                                         ("c"   "compile/comments")
                                         ("C"   "capture/colors")
                                         ("e"   "errors/edit")
                                         ("f"   "files")
                                         ("fC"  "files/convert")
                                         ("fe"  "emacs(spacemacs)")
                                         ("fv"  "variables")
                                         ("g"   "git/versions-control")
                                         ("h"   "help")
                                         ("hd"  "help-describe")
                                         ("i"   "insertion")
                                         ("j"   "jump/join/split")
                                         ("k"   "lisp")
                                         ("kd"  "delete")
                                         ("kD"  "delete-backward")
                                         ("k`"  "hybrid")
                                         ("n"   "narrow/numbers")
                                         ("o"   "org")
                                         ("p"   "projects")
                                         ("p$"  "projects/shell")
                                         ("q"   "quit")
                                         ("r"   "registers/rings/resume")
                                         ("Re"  "elisp")
                                         ("Rp"  "pcre")
                                         ("s"   "search/symbol")
                                         ("sa"  "ag")
                                         ("sg"  "grep")
                                         ("sk"  "ack")
                                         ("st"  "pt")
                                         ("sw"  "web")
                                         ("t"   "toggles")
                                         ("tC"  "colors")
                                         ("tE"  "editing-styles")
                                         ("th"  "highlight")
                                         ("tm"  "modeline")
                                         ("T"   "UI toggles/themes")
                                         ("C-t" "other toggles")
                                         ("w"   "windows")
                                         ("wp"  "popup")
                                         ("x"   "text")
                                         ("xa"  "align")
                                         ("xd"  "delete")
                                         ("xg"  "google-translate")
                                         ("xl"  "lines")
                                         ("xm"  "move")
                                         ("xt"  "transpose")
                                         ("xw"  "words")
                                         ("z"   "zoom")))
  (mapc (lambda (x) (apply #'spacemacs/declare-prefix x))
        spacemacs/key-binding-prefixes)
  ;;; customize key binding prefixes ends here
  )
