(configuration-layer/declare-layers '(
                                      nicolas4d-auto-completion
                                      nicolas4d-base
                                      nicolas4d-better-defaults
                                      nicolas4d-chinese
                                      nicolas4d-editing
                                      nicolas4d-helm
                                      nicolas4d-html
                                      nicolas4d-ivy
                                      nicolas4d-javascript
                                      nicolas4d-latex
                                      nicolas4d-layouts
                                      nicolas4d-mail
                                      nicolas4d-minor-mode
                                      nicolas4d-org
                                      nicolas4d-package
                                      nicolas4d-plantuml
                                      nicolas4d-python
                                      nicolas4d-search
                                      nicolas4d-spell-checking
                                      nicolas4d-tags
                                      emacs-lisp
                                      python
                                      c-c++
                                      ivy
                                      markdown
                                      ranger
                                      version-control
                                      yaml
                                      csv
                                      sql
                                      git
                                      github
                                      ))
